export default class ConstantUI {

  static readonly FONT_SIZE_TITLE: number = 18
  static readonly FONT_SIZE_SUBTITLE: number = 16
  static readonly FONT_SIZE_MESSAGE: number = 14

  static readonly BUTTON_WIDTH: string = '80%'
  static readonly BUTTON_HEIGHT_PRIMARY: number = 44
  static readonly BUTTON_HEIGHT_SECONDARY: number = 40


  static readonly COLUMN_SPACE: number = 12


  static readonly BATTERY_INTERVAL: number = 15000
  static readonly NOTIFICATION_ID: number = 7001


  static readonly SPLASH_DELAY_MS: number = 2000
  static readonly FULL_WIDTH: string = '100%'
  static readonly FULL_HEIGHT: string = '100%'


  static readonly TRANSITION_ENTER_DURATION: number = 400
  static readonly TRANSITION_EXIT_DURATION: number = 400


  static readonly RES_LOTTIE_REMINDER: string = 'resources/rawfile/charging_battery.json'
}
